apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1 
  labels:    #replica set labels
    name: app1 
    tier: frontend 
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:  #these are used to select the pod to create replicas
      name: app1 
      tier: frontend 
  template:   #this is pod template
    metadata:
      labels:  #these labels belongs to pod 
        name: app1 
        tier: frontend 
    spec:
      containers:
      - name: app1 
        image: santhan29/app1:v1 
---
kind: Service
apiVersion: v1
metadata:
 name: app1 
spec: 
  selector:
    name: app1 
    tier: frontend 
  ports:
    - name: nginx-service-port
      protocol: TCP
      port: 80  #service port
      targetPort: 80 #container port 
